name: namaz
on:
  schedule:
    - cron: "25,55 * * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  halal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          bash -c "$(curl -ZLf https://astral.sh/uv/install.sh)"
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"

      - name: Install dependencies
        run: uv sync

      - name: Run python
        run: uv run ./main.py
        env:
          TOKEN: ${{ secrets.TOK }}

#      - name: Install dependencies
#        run: |
#          pip install -r ./requirements.txt
#
#      - name: Run python
#        run: python3 ./main.py
#        env:
#          TOKEN: ${{ secrets.TOK }}
